version: "3"

services:
  blog:
    image: "python:latest"
    build: "."
    hostname: "blog"
    container_name: "blog"
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    volumes:
      - "./src:/app"
    restart: "unless-stopped"
